# Generated by Django 4.2.9 on 2024-01-26 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zenapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZenCoins",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="zenapp.usermodel",
                    ),
                ),
                ("zen_coins", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
